--Pickle Jar in Moe's
Game.GagBegin("gag_jar.p3d")
	Game.GagSetInterior("moe1")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Pickle")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_jar")
	Game.GagSetTrigger("action","PickleTrig",1.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Flaming Moe in Moe's
Game.GagBegin("gag_flm.p3d")
	Game.GagSetInterior("moe1")
	Game.GagSetCycle("single")
	Game.GagSetPosition("FlaMoe")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_flm")
	Game.GagSetTrigger("action","FlaMoeTrig",1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Love Tester in Moe's
Game.GagBegin("gag_love.p3d")
	Game.GagSetInterior("moe1")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Love")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_love")
	Game.GagSetTrigger("action","LoveTrig",.75)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Slot Machine in Moe's
Game.GagBegin("gag_slot.p3d")
	Game.GagSetInterior("moe1")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Slots")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_slot")
	Game.GagSetTrigger("action","SlotsTrig",.75)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Cat-apult
Game.GagBegin("gag_cata.p3d")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(119.535,7.196,52.412)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_cata")
	Game.GagSetTrigger("action",122.543,7.725,50.876,1.6)
	Game.GagSetAnimCollision(1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Fat Tony's Construction
Game.GagBegin("gag_tony.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-6.87,7.444,-40.132)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_tony")
	Game.GagSetTrigger("action",-8.436,5.401,-42.758,4.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

--- Herman's Bomb
Game.GagBegin("gag_bomb.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-327.546,7.384,370.651)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_bomb")
	Game.GagSetTrigger("action",-325.029,7.384,372.853,2.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Rat Milker
Game.GagBegin("gag_milk.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-209.835,23.284,44.135)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_milk")
	Game.GagSetTrigger("action",-210.282,23.132,46.604,4)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Exploding Car
Game.GagBegin("gag_car.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-304.935,8.133,406.144)
	Game.GagSetSparkle(1)
	Game.GagSetCoins(5,-1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_car")
	Game.GagSetTrigger("action",-305.108,8.016,405.407,1.8)
	Game.GagSetAnimCollision(1)
	Game.GagSetPersist(1)
Game.GagEnd()

-- Moleman get's picture taken in the DMV
Game.GagBegin("gag_mol2.p3d")
	Game.GagSetInterior("dmv")
	Game.GagSetCycle("single")
	Game.GagSetPosition(0.218,-20.009,-199.939)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_mol2")
	Game.GagSetTrigger("action",4.349,-19.994,-208.487,1.43)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Dumpster Gag
Game.GagBegin("l2_dump.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-47.669,28.76,393.687)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_lvl2_dumpster")
	Game.GagSetTrigger("action",-47.123,28.76,395.356,2.4)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

if not Settings.DisableNewGags then
	-- ...?
	Game.GagBegin("gag_tele.p3d")
		Game.GagPlayFMV("l2bump.rmv")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(-122.766, 28.89062,	510.4898)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_loot")
		Game.GagSetTrigger("action", -122.766, 28.89062,	510.4898, .864)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()
end