-- Radioactive Man
Game.GagBegin("gag_racm.p3d")
	Game.GagSetInterior("Android")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Radio")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_racm")
	Game.GagSetTrigger("action","RadioTrig",1.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Clank Clank Robot
Game.GagBegin("gag_clnk.p3d")
	Game.GagSetInterior("Android")
	Game.GagSetCycle("single")
	Game.GagSetPosition("Robot")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_clnk")
	Game.GagSetTrigger("action","RobotTrig",1.2)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Movie Ticket
Game.GagBegin("gag_ismv.p3d")
	Game.GagSetInterior("Android")
	Game.GagSetPosition(0.8,-19.1,-346.55)
	Game.GagSetRandom(0)
	Game.GagSetCycle("reset")
	Game.GagCheckCollCards("cbg","lisa","rewardsuccess","rewardintro","rewardfail") --char1, char2, accept, instruct, reject.
	Game.GagSetTrigger("action",0.8,-19,-347,1.5)
	Game.GagSetSparkle(1)
Game.GagEnd()

-- Movie
Game.GagBegin("gag_ismv.p3d")
	Game.GagSetPosition(-140,-33,-121)
	Game.GagSetRandom(0)
	Game.GagSetCycle("reset")
	Game.GagCheckMovie("teen","lisa","fmv8.rmv","aztec") --char1, char2, fmv, reject.
	Game.GagSetTrigger("action",-140,-31,-121,2.0)
Game.GagEnd()

-- Blowup Doll Gag
--Game.GagBegin("gag_blow.p3d")
	--Game.GagSetInterior("Android")
	--Game.GagSetCycle("single")
	--Game.GagSetPosition(Doll)
	--Game.GagSetRandom(0)
	--Game.GagSetSound("gag_blow")
	--Game.GagSetTrigger("action",DollTrig,1)
--Game.GagEnd()

-- Kamp Krusty Flag
Game.GagBegin("gag_flag.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(61.628,-20.112,315.541)
	Game.GagSetSparkle(1)
	Game.GagSetIntro(80)
	Game.GagSetOutro(80)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_flag")
	Game.GagSetTrigger("action",62.417,-20.147,315.512,2.1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Kamp Krusty Pig on a Stick
Game.GagBegin("gag_pig.p3d")
	Game.GagSetCycle("cycle")
	Game.GagSetPosition(70.375,-20.133,335.162)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_pig")
	Game.GagSetTrigger("action",70.428,-19.504,335.216,3.625)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- SILENT ALARM ACTIVATED!
Game.GagBegin("gag_alrm.p3d")
	Game.GagSetInterior("Observatory")
	Game.GagSetCycle("single")
	Game.GagSetPosition("SAlarm")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_alrm")
	Game.GagSetTrigger("action",149.979,-20,-358.705,2)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Matter Transporter
Game.GagBegin("gag_matt.p3d")
	Game.GagSetInterior("Observatory")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Tele")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_matt")
	Game.GagSetTrigger("action","TeleTrig",2.503)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Perpetual Motion Machine
Game.GagBegin("gag_perp.p3d")
	Game.GagSetInterior("Observatory")
	Game.GagSetCycle("cycle")
	Game.GagSetPosition("Perp")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_perp")
	Game.GagSetTrigger("action","PerpTrig",1.308)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,1)
Game.GagEnd()

-- Crane that spills hot pants
Game.GagBegin("gag_pant.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-417.344,-58.909,59.234)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_pant")
	Game.GagSetTrigger("action",-421.022,-59.036,60.075,2.6)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
	Game.GagSetAnimCollision(1)
Game.GagEnd()

-- Wally Weazles Ball Room
Game.GagBegin("gag_kids.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(45.808,.521,-22.388)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_kids")
	Game.GagSetTrigger("action",46.243,-1.302,-25.587,2.58)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Telescope
Game.GagBegin("gag_tele.p3d")
	Game.GagSetInterior("Observatory")
	Game.GagPlayFMV("tele.rmv")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(151.225,-25.789,-352.077)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_tele")
	Game.GagSetTrigger("action",151.225,-19.789,-352.077,.907)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Dumpster
Game.GagBegin("l3_dump.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(62.401,7.037,39.72)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_lvl6_dumpster")
	Game.GagSetTrigger("action",63.11,7.026,38.072,2.4)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- ...?
if not Settings.DisableNewGags then
	Game.GagBegin("gag_tele.p3d")
		Game.GagPlayFMV("l3bump.rmv")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(88.95258, 4.227133, -90.96965)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_loot")
		Game.GagSetTrigger("action", 88.95258, 4.227133, -90.96965, .864)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()
end