Game.SelectMission("m1sd")
	Game.SetMissionResetPlayerOutCar("m1_bart_start","m1_current_carstart")
	Game.SetDynaLoadData("l2z1.p3d;l2r1.p3d;l2r4.p3d;")
	Game.UsePedGroup(0)
	Game.SetPresentationBitmap("art/banners/l2m1bnnr.p3d")
	
	Game.SetInitialWalk("m1_bart_walkto")
	
	Game.SetMissionStartCameraName("mission1camShape")
	Game.SetMissionStartMulticontName("mission1cam")
	Game.SetAnimatedCameraName("mission1camShape") 
	Game.SetAnimCamMulticontName("mission1cam")
	
	Game.AddStage(0)
		Game.SetHUDIcon("milhouse")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(5)
		
		Game.AddObjective("talkto","neither")
			Game.AddNPC("milhouse","m1_milhouse_start")
			Game.SetTalkToTarget("milhouse",0,-0.5)
		Game.CloseObjective()
	Game.CloseStage()	

	Game.AddStage(1)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_far")
			Game.SetConversationCam(2,"pc_far")
			Game.SetConversationCam(3,"npc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_scratch_head")
			Game.AddAmbientNpcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.SetDialogueInfo("bart","milhouse","bonestorm",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()