Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\hermans.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\moes.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\townhall.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\police.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\wiggu_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\moe.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\snake.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\otto.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\ralph.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\firework.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\barrel.p3d")

Game.LoadP3DFile("art\\icons\\cars\\car_icon.p3d")
Game.LoadP3DFile("art\\icons\\cars\\moe_v.p3d")
Game.LoadP3DFile("art\\locators\\l2m2.p3d")
Game.LoadP3DFile("art\\pickups\\fireworks.p3d")

Game.LoadDisposableCar("art\\cars\\scorp_v.p3d","scorp_v","OTHER")
Game.LoadDisposableCar("art\\cars\\moe_v.p3d","moe_v","AI")
Game.LoadDisposableCar("art\\cars\\wiggu_v.p3d","wiggu_v","AI")