Game.SelectMission("m2sd")
	Game.SetMissionResetPlayerOutCar("m2_bart_start","m2_current_carstart")
	Game.SetDynaLoadData("l2z3.p3d;l2r2.p3d;l2r3.p3d;")
	Game.SetPresentationBitmap("art/banners/l2m2bnnr.p3d")

	Game.UsePedGroup(4)

	Game.SetMissionStartCameraName("mission2camShape")
	Game.SetMissionStartMulticontName("mission2cam")
	Game.SetAnimatedCameraName("mission2camShape") 
	Game.SetAnimCamMulticontName("mission2cam")
	
	Game.AddStage(0)
		Game.SetHUDIcon("hermans")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(5)
		
		Game.AddStageVehicle("scorp_v","m2_scorp_v_carstart","NULL","missions\\l2m2\\scorp_v.con")
		
		Game.AddObjective("goto")
			Game.AddNPC("kearney","m2_kearney_start")
			Game.SetDestination("m2_hermans","carsphere")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0) Game.RESET_TO_HERE()
		Game.SetHUDIcon("kearney")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("talkto")
			Game.AddNPC("kearney","m2_kearney_start")
			Game.SetTalkToTarget("kearney",0,-0.5)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.SetDialogueInfo("bart","kearney","fireworks",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()