Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\java.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\frink.p3d")
Game.LoadP3DFile("art\\effects\\bonestorm_explosion.p3d")

Game.LoadP3DFile("art\\icons\\cars\\car_icon.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cNerd.p3d")
Game.LoadP3DFile("art\\icons\\cars\\ironman.p3d")
Game.LoadP3DFile("art\\locators\\l2m3.p3d")
Game.LoadP3DFile("art\\pickups\\bloodbag.p3d")
Game.LoadP3DFile("art\\pickups\\fish.p3d")
Game.LoadP3DFile("art\\pickups\\lasergun.p3d")
Game.LoadP3DFile("art\\pickups\\monkey.p3d")
Game.LoadP3DFile("art\\pickups\\tomacco.p3d")

Game.LoadDisposableCar("art\\cars\\comic_v.p3d","comic_v","OTHER")
Game.LoadDisposableCar("art\\cars\\cNerd.p3d","cNerd","AI")
Game.LoadDisposableCar("art\\cars\\ironman.p3d","ironman","AI")