Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\cvan_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\hermans.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\stadium.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\kburger.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\wiggum.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\snake.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\radio.p3d")
Game.LoadP3DFile("art\\missions\\generic\\fline.p3d")
	
Game.LoadP3DFile("art\\icons\\cars\\bbman_v.p3d")
Game.LoadP3DFile("art\\icons\\locations\\highway.p3d")
Game.LoadP3DFile("art\\icons\\misc\\myst.p3d")
Game.LoadP3DFile("art\\effects\\bonestorm_explosion.p3d")
Game.LoadP3DFile("art\\locators\\l2m4.p3d")
Game.LoadP3DFile("art\\pickups\\radio.p3d")
Game.LoadP3DFile("art\\pickups\\krusty_meal.p3d")
Game.LoadP3DFile("art\\pickups\\fish.p3d")
Game.LoadP3DFile("art\\pickups\\fireworks.p3d")
Game.LoadP3DFile("art\\pickups\\icecream_tub.p3d")
Game.LoadP3DFile("art\\pickups\\cooler.p3d")
Game.LoadP3DFile("art\\pickups\\bloodbag.p3d")
Game.LoadP3DFile("art\\pickups\\pills_trucker.p3d")
Game.LoadP3DFile("art\\pickups\\folder.p3d")

Game.LoadDisposableCar("art\\cars\\wiggu_v.p3d","wiggu_v","OTHER")
Game.LoadDisposableCar("art\\cars\\snake_v.p3d","snake_v","AI")
Game.LoadDisposableCar("art\\cars\\bbman_v.p3d","bbman_v","AI")
Game.LoadDisposableCar("art\\cars\\cletu_v.p3d","cletu_v","AI")