Game.SelectMission("m4sd")
	Game.SetMissionResetPlayerOutCar("m4_bart_start","m4_current_carstart")
	Game.SetDynaLoadData("l2z1.p3d;l2r1.p3d;l2r4.p3d;")
	Game.UsePedGroup(6)
	Game.SetPresentationBitmap("art/banners/l2m4bnnr.p3d")

	Game.SetMissionStartCameraName("mission2camShape")
	Game.SetMissionStartMulticontName("mission2cam")
	Game.SetAnimatedCameraName("mission2camShape")
	Game.SetAnimCamMulticontName("mission2cam")
	
	Game.AddStage(0)
		Game.RESET_TO_HERE()
		Game.SetHUDIcon("frink")
		Game.SetStageMessageIndex(1)
		
		Game.AddStageVehicle("ironman","m4_frink_v_carstart","NULL","missions\\l2m4\\frink_v.con")
		
		Game.AddObjective("talkto")
			Game.AddNPC("frink","m4_frink_start")
			Game.SetTalkToTarget("frink",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.AddStageVehicle("wiggu_v","m4_wiggu_v_carstart","NULL","missions\\l2m4\\wiggu_v.con")
		
		Game.AddObjective("dialogue")
			Game.AddNPC("frink","m4_frink_start")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_near")
			Game.SetConversationCam(2,"pc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_no")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.SetCamBestSide("m4_bestside")
			Game.SetDialogueInfo("bart","frink","gimme",0)
			Game.SetDialoguePositions("m4_bart_start","m4_frink_start","m4_current_carstart")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("hermans")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("goto")
			Game.AddNPC("wiggum","m4_wiggum_start")
			Game.SetDestination("m4_hermans","carsphere")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("wiggum")
		Game.SetStageMessageIndex(3)
		
		Game.AddObjective("talkto")
			Game.SetTalkToTarget("wiggum",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.AddNPC("wiggum","m4_wiggum_start")
			Game.AmbientAnimationRandomize(1,0)--(pc=0,npc=1)(nonrandom=0,random=1)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_far")
			Game.SetConversationCam(2,"pc_far")
			Game.SetConversationCam(3,"npc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_hands_on_hips")
			Game.AddAmbientPcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("dialogue_scratch_head")
			Game.AddAmbientPcAnimation("none")
			Game.SetCamBestSide("m4_bestside2")
			Game.SetDialogueInfo("bart","wiggum","finest",0)
			Game.SetDialoguePositions("m4_bart_finest","m4_wiggum_finest","m4_wiggu_v_carstart")
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()