Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\drnick.p3d" )
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\scream.p3d" )
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\monkey.p3d" )
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\blender.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\lbsc.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\trynsave.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\blimo_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\cvan_v.p3d")
	
Game.LoadP3DFile("art\\icons\\cars\\animctrl.p3d")
Game.LoadP3DFile("art\\icons\\locations\\downtown.p3d")
Game.LoadP3DFile("art\\locators\\l2m6.p3d")
Game.LoadP3DFile("art\\pickups\\blender.p3d")
Game.LoadP3DFile("art\\pickups\\monkey.p3d")

Game.LoadDisposableCar("art\\cars\\animctrl.p3d","animctrl","AI")