Game.SelectMission("m6sd")
	Game.SetMissionResetPlayerOutCar("m6_bart_start","m6_current_carstart")
	Game.SetDynaLoadData("l2z4.p3d;l2z1.p3d;l2r4.p3d;")
	Game.UsePedGroup(6)
	Game.SetPresentationBitmap("art/banners/l2m6bnnr.p3d")
	
	Game.SetMissionStartCameraName("mission6camShape")
	Game.SetMissionStartMulticontName("mission6cam")
	Game.SetAnimatedCameraName("mission6camShape")
	Game.SetAnimCamMulticontName("mission6cam")

	Game.AddStage(0) Game.RESET_TO_HERE()
		Game.SetHUDIcon("frink")
		Game.SetStageMessageIndex(66)
		
		Game.AddObjective("talkto")
			Game.AddNPC("frink","m6_frink_start")
			Game.SetTalkToTarget("frink",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"npc_far")
			Game.SetConversationCam(1,"pc_near")
			Game.AddAmbientNpcAnimation("dialogue_no")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_thinking")
			Game.SetDialogueInfo("bart","frink","blender",0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetHUDIcon("scream")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("goto")
			Game.AddNPC("nriviera","m6_nriviera_start")
			Game.SetDestination("m6_screamingmonkey","carsphere")
			Game.TurnGotoDialogOff()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetHUDIcon("drnick")
		Game.SetStageMessageIndex(3)
		
		Game.AddObjective("talkto")
			Game.AddNPC("nriviera","m6_nriviera_start")
			Game.SetTalkToTarget("nriviera",0,0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_near")
			Game.SetConversationCam(2,"pc_far")
			Game.SetConversationCam(3,"npc_near")
			Game.SetConversationCam(4,"pc_far")
			Game.SetConversationCam(5,"npc_near")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_hands_in_air")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_scratch_head")
			Game.AddAmbientPcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("none")
			Game.SetDialogueInfo("bart","nriviera","monkey2",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()