Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\frink.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\stadium.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\townhall.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\moes.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\trynsave.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\celph_v.p3d")
	
Game.LoadP3DFile("art\\effects\\stand_cellphone_explosion.p3d")
Game.LoadP3DFile("art\\icons\\cars\\drone.p3d")
Game.LoadP3DFile("art\\icons\\items\\cellstnd.p3d")
Game.LoadP3DFile("art\\icons\\locations\\downtown.p3d")
Game.LoadP3DFile("art\\locators\\l2m7.p3d")
Game.LoadP3DFile("art\\pickups\\stand_cellphone.p3d")
Game.LoadP3DFile("art\\pickups\\garbage_can.p3d")
Game.LoadP3DFile("art\\pickups\\iphone.p3d")
Game.LoadP3DFile("art\\pickups\\newspaper.p3d")

Game.LoadDisposableCar("art\\cars\\cCellA.p3d","cCellA.p3d","AI")
Game.LoadDisposableCar("art\\cars\\cCellB.p3d","cCellB.p3d","AI")
Game.LoadDisposableCar("art\\cars\\cCellC.p3d","cCellC.p3d","AI")
Game.LoadDisposableCar("art\\cars\\cCellD.p3d","cCellD.p3d","AI")
Game.LoadDisposableCar("art\\cars\\drone.p3d","drone.p3d","AI")