Game.SelectMission("m7sd")
	Game.SetMissionResetPlayerOutCar("m7_bart_start","m7_current_carstart")
	Game.SetDynaLoadData("l2z1.p3d;l2z4.p3d;l2r4.p3d;")
	Game.UsePedGroup(6)
	Game.SetPresentationBitmap("art/banners/l2m7bnnr.p3d")
	
	Game.SetMissionStartCameraName("mission4camShape")
	Game.SetMissionStartMulticontName("mission4cam")
	Game.SetAnimatedCameraName("mission4camShape")
	Game.SetAnimCamMulticontName("mission4cam")

	Game.AddStage(0)
		Game.SetHUDIcon("stadium")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(4)
		
		Game.AddObjective("goto")
			Game.AddNPC("frink","m7_frink_start")
			Game.SetDestination("m7_stadium","carsphere")
		Game.CloseObjective()
	Game.CloseStage()	

	Game.AddStage(0) Game.RESET_TO_HERE()
		Game.SetHUDIcon("frink")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("talkto")
			Game.AddNPC("frink","m7_frink_start")
			Game.SetTalkToTarget("frink",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_near")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.SetCamBestSide("dm_m4_bestside")
			Game.SetDialogueInfo("bart","frink","doodad",0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetHUDIcon("downtown")
		Game.SetStageMessageIndex(3)
		
		Game.AddStageVehicle("cCellA","m7_cCellA_carstart","NULL","missions\\l2m7\\cCellA.con")
		
		Game.AddObjective("goto")
			Game.SetDestination("m7_downtown","carsphere")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()	
		Game.SetHUDIcon("celph_v")
		Game.SetStageMessageIndex(4)
	
		Game.AddObjective("goto")
			Game.SetDestination("m7_askcelluser","triggersphere")
			Game.MustActionTrigger()
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()