Game.SetPresentationBitmap("/GameData/art/banners/l3b1bnnr.p3d")

Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\squidp.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\spsign.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\nelson.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\skinner.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\bonestor.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\skinn_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\noise.p3d")

Game.LoadP3DFile("art\\icons\\items\\racedk.p3d")
Game.LoadP3DFile("art\\locators\\l3bm1.p3d")
Game.LoadP3DFile("art\\pickups\\crate_bonestorm.p3d")
Game.LoadP3DFile("art\\pickups\\cream.p3d")
Game.LoadP3DFile("art\\pickups\\krusty_meal.p3d")
Game.LoadP3DFile("art\\pickups\\laundry.p3d")

Game.LoadDisposableCar("art\\cars\\skinn_v.p3d","skinn_v","OTHER")
Game.LoadDisposableCar("art\\cars\\dol_v.p3d","dol_v","AI")
Game.LoadDisposableCar("art\\cars\\cBone.p3d","cBone","AI")
Game.LoadDisposableCar("art\\cars\\scorp_v.p3d","scorp_v","AI")
Game.LoadDisposableCar("art\\cars\\cCellC.p3d","cCellC","AI")
Game.LoadDisposableCar("art\\cars\\oblit_v.p3d","oblit_v","AI")