Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\itcstore.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\android.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\comic.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\cbg.p3d")
Game.LoadP3DFile("art\\missions\\generic\\fline.p3d")
	
Game.LoadP3DFile("art\\icons\\cars\\car_icon.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cNerd.p3d")
Game.LoadP3DFile("art\\icons\\chars\\male2.p3d")
Game.LoadP3DFile("art\\icons\\items\\racenerd.p3d")
Game.LoadP3DFile("art\\locators\\l3m1.p3d")
Game.LoadP3DFile("art\\pickups\\comic_is.p3d")

Game.LoadDisposableCar("art\\cars\\comic_v.p3d","comic_v","OTHER")

Game.LoadDisposableCar("art\\cars\\cNerd.p3d","cNerd","AI")
Game.LoadDisposableCar("art\\cars\\cNerdB.p3d","cNerdB","AI")
Game.LoadDisposableCar("art\\cars\\cNerdO.p3d","cNerdO","AI")
Game.LoadDisposableCar("art\\cars\\cNerdG.p3d","cNerdG","AI")
Game.LoadDisposableCar("art\\cars\\cNerdP.p3d","cNerdP","AI")