Game.SelectMission("m1sd")
	Game.SetMissionResetPlayerOutCar("m1_lisa_start","m1_current_carstart")
	Game.SetDynaLoadData("l3z1.p3d;l3r1.p3d;l3r5.p3d;l3r5_dam.p3d;")
	Game.UsePedGroup(0)
	Game.SetPresentationBitmap("art/banners/l3m1bnnr.p3d")
	
	Game.SetMissionStartCameraName("mission1camShape")
	Game.SetMissionStartMulticontName("mission1cam")
	Game.SetAnimatedCameraName("mission1camShape")
	Game.SetAnimCamMulticontName("mission1cam")

	Game.SetInitialWalk("m1_lisa_walkto")

	Game.AddStage(0)
		Game.SetHUDIcon("android")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(5)
		
		Game.AddObjective("interior")
			Game.SetDestination("Android")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(5)
		Game.SetStageMessageIndex(2)
		Game.SetHUDIcon("cbg")
		Game.AddObjective("talkto","neither")
			Game.AddNPC("cbg","m1_cbg_start")
			Game.SetTalkToTarget("cbg",0,-0.2,"3.0")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_hands_in_air")
			Game.AddAmbientPcAnimation("dialogue_hands_on_hips")
			Game.AddAmbientPcAnimation("none")
			Game.SetDialogueInfo("lisa","cbg","brother",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()