Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\wallewea.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\planethy.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\spsign.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\milhouse.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\apu.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\bsedan_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\kburger.p3d")

Game.LoadP3DFile("art\\effects\\bonestorm_explosion.p3d")
Game.LoadP3DFile("art\\icons\\cars\\car_icon.p3d")
Game.LoadP3DFile("art\\icons\\cars\\thrill_v.p3d")
Game.LoadP3DFile("art\\icons\\cars\\firebird.p3d")
Game.LoadP3DFile("art\\icons\\locations\\spft.p3d")
Game.LoadP3DFile("art\\icons\\locations\\planetft.p3d")
Game.LoadP3DFile("art\\locators\\l3m2.p3d")
Game.LoadP3DFile("art\\pickups\\buzzcola.p3d")
Game.LoadP3DFile("art\\pickups\\pills_aggroleve.p3d")
Game.LoadP3DFile("art\\pickups\\icecream_tub.p3d")
Game.LoadP3DFile("art\\pickups\\pills_trucker.p3d")
Game.LoadP3DFile("art\\pickups\\cooler.p3d")

Game.LoadDisposableCar("art\\cars\\thrill_v.p3d","thrill_v","AI")
Game.LoadDisposableCar("art\\cars\\firebird.p3d","firebird","AI")
Game.LoadDisposableCar("art\\cars\\cFire_v.p3d","cFire_v","AI")
Game.LoadDisposableCar("art\\cars\\cFire_v2.p3d","cFire_v2","AI")