Game.SelectMission("m5sd")
	Game.SetMissionResetPlayerOutCar("m5_lisa_start","m5_current_carstart")
	Game.SetDynaLoadData("l3r2.p3d;l3z2.p3d;l3z3.p3d;")
	Game.UsePedGroup(3)
	Game.SetPresentationBitmap("art/banners/l3m5bnnr.p3d")

	Game.SetAnimatedCameraName("mission5camShape")
	Game.SetAnimCamMulticontName("mission5cam")
	Game.SetMissionStartCameraName("mission5camShape")
	Game.SetMissionStartMulticontName("mission5cam")

	Game.AddStage(0)
		Game.SetHUDIcon("casino")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(3)
		
		Game.AddObjective("goto")	
			Game.AddNPC("wiggum","m5_wiggum_start")
			Game.SetDestination("m5_casino","carsphere")
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(5) Game.RESET_TO_HERE()
		Game.SetHUDIcon("wiggum")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("talkto")
			Game.AddNPC("wiggum", "m5_wiggum_start")
			Game.AddObjectiveNPCWaypoint("wiggum", "m5_wiggum_walk1")
			Game.AddObjectiveNPCWaypoint("wiggum", "m5_wiggum_walk2")
			Game.SetTalkToTarget("wiggum", 0, 0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageMessageIndex(3)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_far")
			Game.SetConversationCam(1,"npc_far")
			Game.SetConversationCam(2,"pc_far")
			Game.SetConversationCam(3,"npc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_scratch_head")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientPcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientPcAnimation("none")
			Game.SetCamBestSide("m5_bestside")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetDialogueInfo("lisa","wiggum","thiefcar",0)
			Game.SetDialoguePositions("m5_lisa_thiefcar","m5_wiggum_thiefcar","m5_current_carstart")
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()