Game.SelectMission("m6sd")
	Game.SetMissionResetPlayerOutCar("m6_lisa_start2","m6_current_carstart")
	Game.SetDynaLoadData("l3r2.p3d;l3z2.p3d;l3z3.p3d;")
	Game.UsePedGroup(3)
	Game.SetPresentationBitmap("art/banners/l3m6bnnr.p3d")
	
	Game.SetAnimatedCameraName("mission5camShape")
	Game.SetAnimCamMulticontName("mission5cam")
	Game.SetMissionStartCameraName("mission5camShape")
	Game.SetMissionStartMulticontName("mission5cam")

	Game.AddStage(5) Game.RESET_TO_HERE()
		Game.SetHUDIcon("wiggum")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(4)
		
		Game.AddStageVehicle("wiggu_v","m6_wiggu_v_carstart","NULL","missions\\l3m6\\wiggu_v.con")
		
		Game.AddObjective("talkto")
			Game.AddNPC("wiggum","m6_wiggum_start")
			Game.AddObjectiveNPCWaypoint("wiggum", "m6_wiggum_walk1")
			Game.AddObjectiveNPCWaypoint("wiggum", "m6_wiggum_walk2")
			Game.SetTalkToTarget("wiggum", 0, 0)
		Game.CloseObjective()
	Game.CloseStage()


	Game.AddStage(0)		
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"npc_far")
			Game.SetConversationCam(1,"pc_far")
			Game.SetConversationCam(2,"npc_far")
			Game.SetConversationCam(3,"npc_far")
			Game.AddAmbientNpcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.SetCamBestSide("m5_bestside")
			Game.SetDialogueInfo("lisa","wiggum","hopin",0)
			Game.SetDialoguePositions("m6_lisa_hopin","m6_wiggum_hopin","m6_current_carstart")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetHUDIcon("wiggu_v")
		Game.SetStageMessageIndex(2)
		
		Game.AddStageVehicle("wiggu_v","m6_wiggu_v_carstart","NULL","missions\\l3m6\\wiggu_v.con")
		
		Game.AddObjective("goto")
			Game.SetDestination("m6_start","triggersphere")
			Game.SetCollectibleEffect("wrench_collect")
			Game.MustActionTrigger()
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()