Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\ship.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\chum.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\duff.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\fish.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\scaptain.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\bart.p3d")

Game.LoadP3DFile("art\\icons\\cars\\car_icon.p3d")
Game.LoadP3DFile("art\\icons\\cars\\thrill_v.p3d")	
Game.LoadP3DFile("art\\icons\\chars\\crwmr.p3d")	
Game.LoadP3DFile("art\\icons\\locations\\kamp.p3d")
Game.LoadP3DFile("art\\icons\\items\\duffcan.p3d")
Game.LoadP3DFile("art\\locators\\l3m7.p3d")
Game.LoadP3DFile("art\\pickups\\diaper.p3d")
Game.LoadP3DFile("art\\pickups\\fish.p3d")
Game.LoadP3DFile("art\\pickups\\duff_can.p3d")

Game.LoadDisposableCar("art\\cars\\thrill_v.p3d","thrill_v","AI")
