Game.SetPresentationBitmap("/GameData/art/banners/l1r1bnnr.p3d")

Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\race.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\krusty_v.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\char\\svt.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\cletus_v.p3d")

Game.LoadP3DFile("art\\icons\\cars\\cNerd.p3d")
Game.LoadP3DFile("art\\icons\\cars\\moe_v.p3d")
Game.LoadP3DFile("art\\icons\\cars\\knigh_v.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cletu_vB.p3d")
Game.LoadP3DFile("art\\icons\\cars\\ironman.p3d")
Game.LoadP3DFile("art\\locators\\l3sr1.p3d")

Game.LoadDisposableCar("art\\cars\\cDuff.p3d","cDuff","AI")
Game.LoadDisposableCar("art\\cars\\cNerd.p3d","cNerd","AI")
Game.LoadDisposableCar("art\\cars\\moe_v.p3d","moe_v","AI")
Game.LoadDisposableCar("art\\cars\\ironman.p3d","ironman","AI")
Game.LoadDisposableCar("art\\cars\\knigh_v.p3d","knigh_v","AI")
Game.LoadDisposableCar("art\\cars\\cletu_vB.p3d","cletu_vB","AI")