Game.SelectMission("m2sd")
	Game.SetMissionResetPlayerOutCar("m2_homer_start","m2_current_carstart")
	Game.SetDynaLoadData("l1z1.p3d;l1r1.p3d;l1r7.p3d;")
	Game.UsePedGroup(0)
	Game.SetPresentationBitmap("art/banners/l1m2bnnr.p3d")
	
	Game.SetMissionStartCameraName("mission2camShape")
	Game.SetMissionStartMulticontName("mission2cam")
	Game.SetAnimatedCameraName("mission2camShape")
	Game.SetAnimCamMulticontName("mission2cam")
	
	Game.AddStage(1)
		Game.SetHUDIcon("simpsons")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(2)
		
		Game.AddObjective("goto")
			Game.AddNPC("marge","m2_marge_start")
			Game.SetDestination("m2_simpsonshouse","carsphere")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(2) Game.RESET_TO_HERE()
		Game.SetHUDIcon("simpsons")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("interior")
			Game.AddNPC("marge","m2_marge_start")
			Game.SetDestination("SimpsonsHouse","simp_mission_doorstar")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(3)
		Game.SetHUDIcon("marge")
		Game.SetStageMessageIndex(3)
		
		Game.AddObjective("talkto")
			Game.AddNPC("marge","m2_marge_start")
			Game.SetTalkToTarget("marge",0,0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetDialogueInfo("homer","marge","neighbor",0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(5)
		Game.SetHUDIcon("simpdoor")
		Game.SetStageMessageIndex(4)
		
		Game.AddObjective("gooutside")
			Game.TurnGotoDialogOff()
			Game.SetDestination("outside_simpsonshouse")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(6)
		Game.SetHUDIcon("ned")
		Game.SetStageMessageIndex(5)
		
		Game.AddObjective("talkto","neither")
			Game.AddNPC("ned","m2_ned_start")
			Game.SetTalkToTarget("ned",0,0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetDialogueInfo("homer","ned","culprit",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()