Game.SelectMission("m4sd")
	Game.SetMissionResetPlayerOutCar("m4_homer_start","m4_current_carstart")
	Game.SetDynaLoadData("l1r4a.p3d;l1z6.p3d;l1r6.p3d;")
	Game.UsePedGroup(7)
	Game.SetPresentationBitmap("art/banners/l1m4bnnr.p3d")

	Game.SetMissionStartCameraName("mission4camShape")
	Game.SetMissionStartMulticontName("mission4cam")
	Game.SetAnimatedCameraName("mission4camShape")
	Game.SetAnimCamMulticontName("mission4cam")
	
	Game.AddStage(1)
		Game.RESET_TO_HERE()
		Game.SetHUDIcon("wstation")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(2)
		
		Game.AddObjective("goto")
			Game.AddNPC("smithers","m4_carl_start")
			Game.SetDestination("m4_workstation","triggersphere")
			Game.SetCollectibleEffect("wrench_collect")
			Game.MustActionTrigger()	
			Game.TurnGotoDialogOff()
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AddNPC("carl","m4_carl_start")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetDialogueInfo("homer","carl","camera",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()