Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\object\\bonestor.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\simpsons.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\school.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\location\\kwike.p3d")
Game.LoadP3DFile("art\\frontend\\dynaload\\images\\msnicons\\vehicle\\celph_v.p3d")

Game.LoadP3DFile("art\\effects\\bonestorm_explosion.p3d")
Game.LoadP3DFile("art\\icons\\locations\\commun.p3d")
Game.LoadP3DFile("art\\icons\\locations\\gasoline.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cCellB.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cCellC.p3d")
Game.LoadP3DFile("art\\icons\\cars\\cCellD.p3d")
Game.LoadP3DFile("art\\locators\\l1m6.p3d")
Game.LoadP3DFile("art\\pickups\\crate_bonestorm.p3d")

Game.LoadDisposableCar("art\\cars\\marge_v.p3d","marge_v","OTHER")
Game.LoadDisposableCar("art\\cars\\cBone.p3d","cBone","AI")
Game.LoadDisposableCar("art\\cars\\cCellB.p3d","cCellB","AI")
Game.LoadDisposableCar("art\\cars\\cCellC.p3d","cCellc","AI")
Game.LoadDisposableCar("art\\cars\\cCellD.p3d","cCellD","AI")