Game.SelectMission("m7sd")
	Game.SetMissionResetPlayerOutCar("m7_homer_start","m7_current_carstart")
	Game.SetDynaLoadData("l1r1.p3d;l1z2.p3d;l1r2.p3d;")
	Game.UsePedGroup(0)
	Game.SetPresentationBitmap("art/banners/l1m7bnnr.p3d")

	Game.SetMissionStartCameraName("mission7camShape")
	Game.SetMissionStartMulticontName("mission7cam")
	Game.SetAnimatedCameraName("mission7camShape")
	Game.SetAnimCamMulticontName("mission7cam")
	
	Game.AddStage(1)
		Game.SetHUDIcon("kwike")
		Game.SetStageMessageIndex(1)
		
		Game.AddObjective("goto")
			Game.AddNPC("carl","m7_carl_start")
			Game.SetDestination("m7_kwikemart","carsphere")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(2)
		Game.RESET_TO_HERE()
		Game.SetHUDIcon("carl")
		Game.SetStageMessageIndex(2)
		
		Game.AddObjective("talkto")
			Game.AddNPC("carl","m7_carl_start")
			Game.SetTalkToTarget("carl",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("dialogue_shake_hand_in_air")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_shaking_fist")
			Game.SetDialogueInfo("homer","carl","stupiddrunk",0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()