-- Store Reward Names (used in the rewards handler and level controllers currently)
-- Cars 1 to 3 are the Default Car, Bonus Mission Car, and the Street Race car.
-- Cars 4 to 7 are forsale.
Rewards = {
	[1] = {
		Cars = {
			[1] = "clfamily",
			[2] = "cletu_v",
			[3] = "auditt",
			[4] = "plowk_v",
			[5] = "cDuff",
			[6] = "statwago",
			[7] = "rocke_v",
		},
		Skins = {
			[1] = "homer",
			[2] = "h_incredi",
			[3] = "h_donut",
			[4] = "h_dt",
			[5] = "h_fat",
		},
		Gags = Settings.DisableNewGags and 15 or 19,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[2] = {
		Cars = {
			[1] = "honor_v",
			[2] = "gramlimo",
			[3] = "moe_v",
			[4] = "mrplo_v",
			[5] = "cLimo",
			[6] = "cFire_v",
			[7] = "catapult",
		},
		Skins = {
			[1] = "bart",
			[2] = "b_slender",
			[3] = "b_white",
			[4] = "b_dark",
			[5] = "b_hugo",
		},
		Gags = 11,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[3] = {
		Cars = {
			[1] = "elect_v",
			[2] = "skinn_v",
			[3] = "waspbike",
			[4] = "otto_v",
			[5] = "cNerd",
			[6] = "bookb_v",
			[7] = "knigh_v",
		},
		Skins = {
			[1] = "lisa",
			[2] = "l_tiedye",
			[3] = "l_sandwich",
			[4] = "l_charging",
			[5] = "l_cool",
		},
		Gags = 11,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[4] = {
		Cars = {
			[1] = "marge_v",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
		},
		Skins = {
			[1] = "marge",
			[2] = "",
			[3] = "",
			[4] = "",
		},
		Gags = Settings.DisableNewGags and 15 or 20,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[5] = {
		Cars = {
			[1] = "wiggu_v",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
		},
		Skins = {
			[1] = "wiggum",
			[2] = "",
			[3] = "",
			[4] = "",
		},
		Gags = 11,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[6] = {
		Cars = {
			[1] = "ironman",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
		},
		Skins = {
			[1] = "frink",
			[2] = "",
			[3] = "",
			[4] = "",
		},
		Gags = 6,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
	[7] = {
		Cars = {
			[1] = "gramp_v",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
		},
		Skins = {
			[1] = "grandpa",
			[2] = "",
			[3] = "",
			[4] = "",
		},
		Gags = 19,
		Wasps = Settings.DisableNewWasps and 20 or 40,
	},
}