Game.AddPurchaseCarReward("gil","gil","npd","shop_npc1",1.3,"shop_car1")
Game.AddPurchaseCarReward("simpson","barney","npd","shop_npc2",1.3,"shop_car2")

Game.AddNPCCharacterBonusMission("milhouse","npd","sr1_milhouse","sr1","checkered","intro",0,"checkeredfinish")
	Game.SetConversationCam(0,"pc_far","sr1")
	Game.SetConversationCam(1,"npc_far","sr1")
	Game.ClearAmbientAnimations("sr1")
	Game.AddAmbientNpcAnimation("dialogue_scratch_head","sr1")
	Game.AddAmbientNpcAnimation("dialogue_no","sr1")
	Game.AddAmbientPcAnimation("dialogue_open_arm_hand_gesture","sr1")
	Game.AddAmbientPcAnimation("dialogue_scratch_head","sr1")
	
Game.AddNPCCharacterBonusMission("nelson","npd","sr2_nelson","sr2","checkered","intro",0,"checkeredfinish")
	Game.SetConversationCam(0,"pc_far","sr2")
	Game.SetConversationCam(1,"npc_far","sr2")
	Game.ClearAmbientAnimations("sr2")
	Game.AddAmbientNpcAnimation("none","sr2")
	Game.AddAmbientNpcAnimation("dialogue_hands_in_air","sr2")
	Game.AddAmbientPcAnimation("dialogue_open_arm_hand_gesture","sr2")
	Game.AddAmbientPcAnimation("dialogue_cross_arms","sr2")

Game.AddNPCCharacterBonusMission("ralph","npd","sr3_ralph","sr3","checkered","intro",0,"checkeredfinish")
	Game.SetConversationCam(0,"pc_far","sr3")
	Game.SetConversationCam(1,"npc_far","sr3")
	Game.ClearAmbientAnimations("sr3")
	Game.AddAmbientNpcAnimation("none","sr3")
	Game.AddAmbientNpcAnimation("dialogue_hands_on_hips","sr3")
	Game.AddAmbientPcAnimation("dialogue_open_arm_hand_gesture","sr3")
	Game.AddAmbientPcAnimation("dialogue_scratch_head","sr3")

Game.AddNPCCharacterBonusMission("louie","npd","sr4_louie","gr1","dice","intro",0,"exclamation_shadow")

if IsModEnabled("ReplayableBonusMissions") then
	Game.AddNPCCharacterBonusMission("cletus","npd","bm1_cletus","bm1","exclamation","chores",0)
else
	Game.AddNPCCharacterBonusMission("cletus","npd","bm1_cletus","bm1","exclamation","chores",1,"exclamation_shadow")
end
	Game.SetConversationCam(0,"pc_near","bm1")
	Game.SetConversationCam(1,"npc_far","bm1")
	Game.SetConversationCam(2,"pc_far","bm1")
	Game.SetConversationCam(3,"npc_near","bm1")
	Game.SetConversationCam(4,"pc_near","bm1")
	Game.SetConversationCam(5,"npc_far","bm1")
	Game.ClearAmbientAnimations("bm1")
	Game.AddAmbientNpcAnimation("dialogue_thinking","bm1")
	Game.AddAmbientNpcAnimation("dialogue_no","bm1")
	Game.AddAmbientNpcAnimation("none","bm1")
	Game.AddAmbientNpcAnimation("dialogue_thinking","bm1")
	Game.AddAmbientNpcAnimation("none","bm1")
	Game.AddAmbientNpcAnimation("dialogue_shake_hand_in_air","bm1")
	Game.AddAmbientPcAnimation("dialogue_scratch_head","bm1")
	Game.AddAmbientPcAnimation("none","bm1")
	Game.AddAmbientPcAnimation("dialogue_yes","bm1")
	Game.AddAmbientPcAnimation("none","bm1")
	Game.AddAmbientPcAnimation("dialogue_hands_in_air","bm1")
	Game.AddAmbientPcAnimation("none","bm1")

Game.AddAmbientCharacter("apu","ambient_apu",1.8)

Game.AddAmbientCharacter("ralph","ambient_ralph",1.3)
	Game.AddAmbientNPCWaypoint("ralph","ambient_ralph_walk1")
	Game.AddAmbientNPCWaypoint("ralph","ambient_ralph_walk2")
	Game.AddAmbientNPCWaypoint("ralph","ambient_ralph_walk3")

Game.AddAmbientCharacter("moleman","ambient_moleman",0)
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk1")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk2")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk3")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk4")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk3")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk2")
	Game.AddAmbientNPCWaypoint("moleman","ambient_moleman_walk1")

Game.AddAmbientCharacter("grandpa","ambient_grandpa",0)
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk1")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk2")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk3")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk4")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk5")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk4")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk3")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk2")
	Game.AddAmbientNPCWaypoint("grandpa","ambient_grandpa_walk1")

Game.AddAmbientCharacter("patty","ambient_patty",1.3)
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk1")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk2")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk3")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk4")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk5")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk4")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk3")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk2")
	Game.AddAmbientNPCWaypoint("patty","ambient_patty_walk1")

Game.AddAmbientCharacter("lisa","ambient_lisa",1.3)

Game.AddAmbientCharacter("willie","ambient_willie",1.3)
	Game.AddAmbientNPCWaypoint("willie","ambient_willie_walk1")
	Game.AddAmbientNPCWaypoint("willie","ambient_willie_walk2")
	Game.AddAmbientNPCWaypoint("willie","ambient_willie_walk3")
	Game.AddAmbientNPCWaypoint("willie","ambient_willie_walk2")
	Game.AddAmbientNPCWaypoint("willie","ambient_willie_walk1")

Game.AddAmbientCharacter("eddie","ambient_eddie",0)
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk1")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk2")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk3")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk4")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk5")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk4")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk3")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk2")
	Game.AddAmbientNPCWaypoint("eddie","ambient_eddie_walk1")

Game.AddAmbientCharacter("krusty","ambient_krusty",0)
	Game.AddAmbientNPCWaypoint("krusty","ambient_krusty_walk1")
	Game.AddAmbientNPCWaypoint("krusty","ambient_krusty_walk2")
	Game.AddAmbientNPCWaypoint("krusty","ambient_krusty_walk3")
	Game.AddAmbientNPCWaypoint("krusty","ambient_krusty_walk2")
	Game.AddAmbientNPCWaypoint("krusty","ambient_krusty_walk1")

Game.AddAmbientCharacter("lenny","ambient_lenny",0)
	Game.AddAmbientNPCWaypoint("lenny","ambient_lenny_walk1")
	Game.AddAmbientNPCWaypoint("lenny","ambient_lenny_walk2")
	Game.AddAmbientNPCWaypoint("lenny","ambient_lenny_walk3")
	Game.AddAmbientNPCWaypoint("lenny","ambient_lenny_walk2")
	Game.AddAmbientNPCWaypoint("lenny","ambient_lenny_walk1")

Game.AddAmbientCharacter("moe","ambient_moe",1.3)
	Game.AddAmbientNPCWaypoint("moe","ambient_moe_walk1")
	Game.AddAmbientNPCWaypoint("moe","ambient_moe_walk2")
	Game.AddAmbientNPCWaypoint("moe","ambient_moe_walk1")
	
Game.AddAmbientCharacter("lucas","ambient_lucas",1.3)

Game.AddAmbientCharacter("frink","ambient_frink",1.3)