-- Barbaque Gag
Game.GagBegin("gag_bbq.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(228.567,3.355,-199.931)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_bbq")
	Game.GagSetTrigger("action",228.567,3.355,-201.097,.812)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Nuclear Gas Gag
Game.GagBegin("gag_gas.p3d")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(11,.998,337)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_gas")
	Game.GagSetTrigger("action",12.35,.998,337,1.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Flander's Bomb Shelter
Game.GagBegin("gag_shel.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(262.601,2.149,-208.027)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_shel")
	Game.GagSetTrigger("action",261.874,2.515,-206.561,1.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Swing Set in the Simpson's Yard
Game.GagBegin("gag_swng.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(221.179,3.766,-204.937)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_swng")
	Game.GagSetTrigger("action",219.314,3.957,-206.512,3.5)
	Game.GagSetAnimCollision(1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Swing Set in the Park
Game.GagBegin("gag_swg2.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(152.941,6.365,-200.761)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_swng")
	Game.GagSetTrigger("action",150.821,6.337,-202.115,3.5)
	Game.GagSetAnimCollision(1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Squishee Machine in the Kwik-E-Mart
Game.GagBegin("gag_sqsh.p3d")
	Game.GagSetInterior("KwikEMart")
	Game.GagSetCycle("single")
	Game.GagSetPosition("Squish")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_sqsh")
	Game.GagSetTrigger("action","SquishTrig",.66)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Jasper in the Freezer in the Kwik-E-Mart
Game.GagBegin("gag_jasp.p3d")
	Game.GagSetInterior("KwikEMart")
	Game.GagSetCycle("single")
	Game.GagSetPosition("Jasper")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_jasp")
	Game.GagSetTrigger("action","JasperTrig",2)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- ATM Machine in the Kwik-E-Mart
Game.GagBegin("gag_atm.p3d")
	Game.GagSetInterior("KwikEMart")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("ATM")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_atm")
	Game.GagSetTrigger("action","ATMTrig",1)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- TV in the Simpson's House
Game.GagBegin("gag_tv.p3d")
	Game.GagSetInterior("SimpsonsHouse")
	Game.GagSetCycle("single")
	Game.GagSetPosition("TV")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_tv")
	Game.GagSetTrigger("action","TVTrig",1.35)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Aztec Mask in the Simpson's Yard
Game.GagBegin("gag_azte.p3d")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(241.347,3.345,-201.126)
	Game.GagSetSparkle(1)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_azte")
	Game.GagSetTrigger("action",240.699,3.366,-201.166,2.82)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Powerplant Melt Down
Game.GagBegin("gag_melt.p3d")
	Game.GagSetCycle("single")
	Game.GagSetPosition(-81.089,2.696,323.139)
	Game.GagSetSparkle(1)
	Game.GagSetIntro(1)
	Game.GagSetOutro(60)
	Game.GagSetRandom(0)
	Game.GagSetCameraShake(.1,450,3.5)
	Game.GagSetSound("gag_melt")
	Game.GagSetTrigger("action",-80.698,-0.008,320.838,1.7)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Dead Fire Extinguisher in the School
Game.GagBegin("gag_fire.p3d")
	Game.GagSetInterior("SpringfieldElementary")
	Game.GagSetCycle("single")
	Game.GagSetPosition("Fire")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_fire")
	Game.GagSetTrigger("action","FireTrig",2.057)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Fire Alarm in the School
Game.GagBegin("gag_sknr.p3d")
	Game.GagSetInterior("SpringfieldElementary")
	Game.GagSetCycle("reset")
	Game.GagSetPosition("Alarm")
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_sknr")
	Game.GagSetTrigger("action","AlarmTrig",1.835)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- Larry the Looter
Game.GagBegin("gag_tele.p3d")
	Game.GagSetInterior("KwikEMart")
	Game.GagPlayFMV("loot.rmv")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(505.452,-19.91,-303.307)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_loot")
	Game.GagSetTrigger("action",506.452,-19.91,-303.307,.5)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

-- SILENT ALARM ACTIVATED!
Game.GagBegin("gag_alm2.p3d")
	Game.GagSetInterior("KwikEMart")
	Game.GagSetCycle("reset")
	Game.GagSetPosition(504.31,-19.0961,-297.76)
	Game.GagSetRandom(0)
	Game.GagSetSound("gag_alm2")
	Game.GagSetTrigger("action",503.872,-20,-297.024,0.961)
	Game.GagSetPersist(1)
	Game.GagSetCoins(1,-1)
Game.GagEnd()

if not Settings.DisableNewGags then
	-- Simpson's Arcade Machine in the Kwik-E-Mart
	Game.GagBegin("gag_tele.p3d")
		Game.GagSetInterior("KwikEMart")
		Game.GagPlayFMV("arcade.rmv")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(505.452, -20, -303.307)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_loot")
		Game.GagSetTrigger("action", 506.009, -20.000,-304.296, .5)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()

	-- Mary Go Round in the Park
	Game.GagBegin("gag_mgr.p3d")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(146.717,4.989,-183.561)
		Game.GagSetSparkle(1)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_mgr")
		Game.GagSetTrigger("action",146.845,5.76,-183.561,4.429)
		Game.GagSetAnimCollision(1)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1,-1)
	Game.GagEnd()

	-- Mary Go Round in the School Playground
	Game.GagBegin("gag_mgr.p3d")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(-80.708,3.228,-610.232)
		Game.GagSetSparkle(1)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_mgr")
		Game.GagSetTrigger("action", -80.708,4.0,-610.232, 4.429)
		Game.GagSetAnimCollision(1)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()

	-- Swingset in the School Playground
	Game.GagBegin("gag_swg2.p3d")
		Game.GagSetCycle("single")
		Game.GagSetPosition(-89.777,3.417,-601.501)
		Game.GagSetSparkle(1)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_swng")
		Game.GagSetTrigger("action",-92.777,3.387,-601.501, 3.5)
		Game.GagSetAnimCollision(1)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()

	-- ...?
	Game.GagBegin("gag_tele.p3d")
		Game.GagPlayFMV("l1bump.rmv")
		Game.GagSetCycle("reset")
		Game.GagSetPosition(196.849, 12.05763,	-344.4764)
		Game.GagSetRandom(0)
		Game.GagSetSound("gag_loot")
		Game.GagSetTrigger("action", 196.849, 12.05763,	-344.4764, .864)
		Game.GagSetPersist(1)
		Game.GagSetCoins(1, -1)
	Game.GagEnd()
end